### PR TITLE
Giving it back to kamon project.

### PR DESCRIPTION
**Pull request by kennethleider**
I am pretty happy with it at this point.  I am a little worried about it's working in multiple applications at the same time.  But from what I can tell of the opentsdb source code, it should be fine.  I'll start testing that in a couple of weeks.

I may come across some bugs as I begin to use the system-metrics, akka, and traces.

### CODE REVIEW

**Comment by dpsoft** [comment]
@kennethleider  the PR looks very good, I would like to merge it BUT there is one missing piece, not in this repository but in our [documentation website](https://github.com/kamon-io/kamon.io)! yes, I know, it is a bit boring to write docs but it is a necessary thing... so if you could create a simple one page doc explaining what this module does, how it reports data and possibly some screenshots of what kind of visualization or results you can get out of it would be super helpful even for us, to start experimenting with this :D.. take a look at the Datadog, StatsD and New Relic pages on our website to get an idea of what we would like to see there.

**Comment by kennethleider** [comment]
Just noticed this.  I'll get on it next week.

**Comment by dpsoft** [comment]
@kennethleider awesome!!!!

**Comment by dpsoft** [comment]
@kennethleider sorry for the late response :( I just released the 0.6.7 version: https://bintray.com/kamon-io/releases/kamon-opentsdb

**Pull request merged**
